/**
 * Enum matching the backend AuditScope
 */
export enum AuditScope {
    PROGRAM = 'PROGRAM',
    LISTING = 'LISTING',
    TRANSACTION = 'TRANSACTION'
}

/**
 * Enum matching the backend AuditStatus
 */
export enum AuditStatus {
    OPEN = 'OPEN',
    CLOSED = 'CLOSED',
    IN_PROGRESS = 'IN_PROGRESS',
    REVIEW = 'REVIEW'
}

/**
 * Interface matching the Java AuditDTO
 */
export interface AuditDTO {
    auditId?: number;      // Optional because it's generated by the database
    officerId: number;     // ID of the officer conducting the audit
    scope: AuditScope;     // Uses the enum above
    findings: string;      // Summary of audit observations
    date: string;          // Formatted as yyyy-MM-dd
    status: AuditStatus;   // Uses the enum above
}